# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\專題\app\AI-Yoga-Coach\AIYogaCoachInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1661, 837)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/yoga-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#title_frame {\n"
"    border-top-left-radius: 10px;\n"
"    background-color: rgb(170, 255, 255);\n"
"}\n"
"\n"
"#main_frame {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                            stop:0 #E3F2FD, stop:1 #BBDEFB);\n"
"}\n"
"\n"
"#icon_label {\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"    max-height: 30px;\n"
"    max-width: 30px;\n"
"}\n"
"\n"
"#title_frame QPushButton {\n"
"    border: none;\n"
"    width: 50px;\n"
"    height: 40px;\n"
"}\n"
"\n"
"#maximize_btn:hover, #minimize_btn:hover {\n"
"background-color:  #BBDEFB;\n"
"}\n"
"\n"
"#close_btn:hover {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"#close_btn, #title_frame {\n"
"    border-top-right-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_label = QtWidgets.QLabel(self.title_frame)
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap(":/icons/icons/yoga-logo.png"))
        self.icon_label.setObjectName("icon_label")
        self.horizontalLayout_2.addWidget(self.icon_label)
        self.title_label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_2.addWidget(self.title_label)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimize_btn = QtWidgets.QPushButton(self.title_frame)
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-minimize-window-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout.addWidget(self.minimize_btn)
        self.maximize_btn = QtWidgets.QPushButton(self.title_frame)
        self.maximize_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-full-screen-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximize_btn.setIcon(icon2)
        self.maximize_btn.setObjectName("maximize_btn")
        self.horizontalLayout.addWidget(self.maximize_btn)
        self.close_btn = QtWidgets.QPushButton(self.title_frame)
        self.close_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-close-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon3)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.title_frame)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.icon_only_frame = QtWidgets.QFrame(self.main_frame)
        self.icon_only_frame.setStyleSheet("    #icon_only_frame {\n"
"        background-color: #b1dcef;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    #icon_only_frame QPushButton {\n"
"        height:50px;\n"
"        border:none;\n"
"    }\n"
"\n"
"    #icon_only_frame QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }")
        self.icon_only_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_only_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_only_frame.setObjectName("icon_only_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.icon_only_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.home_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-home-page-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon4)
        self.home_btn.setIconSize(QtCore.QSize(30, 30))
        self.home_btn.setCheckable(True)
        self.home_btn.setAutoExclusive(True)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout.addWidget(self.home_btn)
        self.music_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.music_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-musical-note-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.music_btn.setIcon(icon5)
        self.music_btn.setIconSize(QtCore.QSize(30, 30))
        self.music_btn.setCheckable(True)
        self.music_btn.setAutoExclusive(True)
        self.music_btn.setObjectName("music_btn")
        self.verticalLayout.addWidget(self.music_btn)
        self.progress_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.progress_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-chart-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.progress_btn.setIcon(icon6)
        self.progress_btn.setIconSize(QtCore.QSize(30, 30))
        self.progress_btn.setCheckable(True)
        self.progress_btn.setAutoExclusive(True)
        self.progress_btn.setObjectName("progress_btn")
        self.verticalLayout.addWidget(self.progress_btn)
        self.share_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.share_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-share-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.share_btn.setIcon(icon7)
        self.share_btn.setIconSize(QtCore.QSize(30, 30))
        self.share_btn.setCheckable(True)
        self.share_btn.setAutoExclusive(True)
        self.share_btn.setObjectName("share_btn")
        self.verticalLayout.addWidget(self.share_btn)
        self.account_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.account_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-account-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.account_btn.setIcon(icon8)
        self.account_btn.setIconSize(QtCore.QSize(30, 30))
        self.account_btn.setCheckable(True)
        self.account_btn.setAutoExclusive(True)
        self.account_btn.setObjectName("account_btn")
        self.verticalLayout.addWidget(self.account_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.info_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-info-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_btn.setIcon(icon9)
        self.info_btn.setIconSize(QtCore.QSize(30, 30))
        self.info_btn.setCheckable(True)
        self.info_btn.setAutoExclusive(True)
        self.info_btn.setObjectName("info_btn")
        self.verticalLayout_2.addWidget(self.info_btn)
        self.login_out_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.login_out_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-logout-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_out_btn.setIcon(icon10)
        self.login_out_btn.setIconSize(QtCore.QSize(30, 30))
        self.login_out_btn.setCheckable(False)
        self.login_out_btn.setAutoExclusive(False)
        self.login_out_btn.setObjectName("login_out_btn")
        self.verticalLayout_2.addWidget(self.login_out_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addWidget(self.icon_only_frame)
        self.full_menu_frame = QtWidgets.QFrame(self.main_frame)
        self.full_menu_frame.setStyleSheet("\n"
"    #full_menu_frame {\n"
"        background-color:  #b1dcef;\n"
"    }\n"
"\n"
"    /* style for QPushButton */\n"
"    #full_menu_frame QPushButton {\n"
"        border:none;\n"
"        height: 50px;\n"
"        text-align: left;\n"
"    }\n"
"\n"
"    #full_menu_frame QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"\n"
"    #full_menu_frame QPushButton:checked {\n"
"        color: #fff;\n"
"    }")
        self.full_menu_frame.setObjectName("full_menu_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.full_menu_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.full_home_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_home_btn.setFont(font)
        self.full_home_btn.setIcon(icon4)
        self.full_home_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_home_btn.setCheckable(True)
        self.full_home_btn.setAutoExclusive(True)
        self.full_home_btn.setObjectName("full_home_btn")
        self.verticalLayout_3.addWidget(self.full_home_btn)
        self.full_music_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_music_btn.setFont(font)
        self.full_music_btn.setIcon(icon5)
        self.full_music_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_music_btn.setCheckable(True)
        self.full_music_btn.setAutoExclusive(True)
        self.full_music_btn.setObjectName("full_music_btn")
        self.verticalLayout_3.addWidget(self.full_music_btn)
        self.full_progress_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_progress_btn.setFont(font)
        self.full_progress_btn.setIcon(icon6)
        self.full_progress_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_progress_btn.setCheckable(True)
        self.full_progress_btn.setAutoExclusive(True)
        self.full_progress_btn.setObjectName("full_progress_btn")
        self.verticalLayout_3.addWidget(self.full_progress_btn)
        self.full_share_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_share_btn.setFont(font)
        self.full_share_btn.setIcon(icon7)
        self.full_share_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_share_btn.setCheckable(True)
        self.full_share_btn.setAutoExclusive(True)
        self.full_share_btn.setObjectName("full_share_btn")
        self.verticalLayout_3.addWidget(self.full_share_btn)
        self.full_account_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_account_btn.setFont(font)
        self.full_account_btn.setIcon(icon8)
        self.full_account_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_account_btn.setCheckable(True)
        self.full_account_btn.setAutoExclusive(True)
        self.full_account_btn.setObjectName("full_account_btn")
        self.verticalLayout_3.addWidget(self.full_account_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.full_info_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_info_btn.setFont(font)
        self.full_info_btn.setIcon(icon9)
        self.full_info_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_info_btn.setCheckable(True)
        self.full_info_btn.setAutoExclusive(True)
        self.full_info_btn.setObjectName("full_info_btn")
        self.verticalLayout_4.addWidget(self.full_info_btn)
        self.full_login_out_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_login_out_btn.setFont(font)
        self.full_login_out_btn.setIcon(icon10)
        self.full_login_out_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_login_out_btn.setCheckable(False)
        self.full_login_out_btn.setAutoExclusive(False)
        self.full_login_out_btn.setObjectName("full_login_out_btn")
        self.verticalLayout_4.addWidget(self.full_login_out_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addWidget(self.full_menu_frame)
        self.frame_3 = QtWidgets.QFrame(self.main_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menu_btn = QtWidgets.QPushButton(self.frame)
        self.menu_btn.setStyleSheet("padding: 5px;\n"
"border: none;\n"
"width: 35px;\n"
"height: 35px")
        self.menu_btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-hamburger-button-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn.setIcon(icon11)
        self.menu_btn.setIconSize(QtCore.QSize(35, 35))
        self.menu_btn.setCheckable(True)
        self.menu_btn.setAutoExclusive(False)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_6.addWidget(self.menu_btn)
        self.camera_btn = QtWidgets.QPushButton(self.frame)
        self.camera_btn.setEnabled(True)
        self.camera_btn.setStyleSheet("QPushButton {\n"
"    width: 35px;\n"
"    height: 35px;\n"
"    background-color: transparent; \n"
"    border: none;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #ff6c7b;\n"
"     border-radius: 5px;\n"
"     border: 1px solid;\n"
"}")
        self.camera_btn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-camera-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.camera_btn.setIcon(icon12)
        self.camera_btn.setIconSize(QtCore.QSize(35, 35))
        self.camera_btn.setCheckable(True)
        self.camera_btn.setChecked(False)
        self.camera_btn.setObjectName("camera_btn")
        self.horizontalLayout_6.addWidget(self.camera_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.account_status_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.account_status_label.setFont(font)
        self.account_status_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.account_status_label.setObjectName("account_status_label")
        self.horizontalLayout_6.addWidget(self.account_status_label)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setStyleSheet("QWidget {\n"
"    background-color: #D1E9E9; /* 淺綠色 */\n"
"}\n"
"")
        self.home_page.setObjectName("home_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_1 = QtWidgets.QWidget(self.home_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(sizePolicy)
        self.widget_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget_1.setObjectName("widget_1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.camera_label = QtWidgets.QLabel(self.widget_1)
        self.camera_label.setMinimumSize(QtCore.QSize(720, 405))
        self.camera_label.setMaximumSize(QtCore.QSize(720, 405))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.camera_label.setFont(font)
        self.camera_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camera_label.setStyleSheet("QLabel {\n"
"    background-color: gray;  /* 設定背景顏色為灰色 */\n"
"    border-radius: 15px;     /* 設定邊角圓滑，數值越大越圓 */\n"
"    color: white;            /* 設定文字顏色為白色，讓字更清楚 */\n"
"    text-align: center;      /* 水平置中，Qt 不支援此屬性，要用對齊方式 */\n"
"    qproperty-alignment: AlignCenter;  /* Qt 標準方式設定文字置中 */\n"
"}\n"
"")
        self.camera_label.setObjectName("camera_label")
        self.horizontalLayout_8.addWidget(self.camera_label)
        self.demo_label = QtWidgets.QLabel(self.widget_1)
        self.demo_label.setMinimumSize(QtCore.QSize(440, 405))
        self.demo_label.setMaximumSize(QtCore.QSize(400, 405))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.demo_label.setFont(font)
        self.demo_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.demo_label.setStyleSheet("QLabel {\n"
"    background-color: gray;  /* 設定背景顏色為灰色 */\n"
"    border-radius: 15px;     /* 設定邊角圓滑，數值越大越圓 */\n"
"    color: white;            /* 設定文字顏色為白色，讓字更清楚 */\n"
"    text-align: center;      /* 水平置中，Qt 不支援此屬性，要用對齊方式 */\n"
"    qproperty-alignment: AlignCenter;  /* Qt 標準方式設定文字置中 */\n"
"}\n"
"")
        self.demo_label.setObjectName("demo_label")
        self.horizontalLayout_8.addWidget(self.demo_label)
        self.deom_list = QtWidgets.QListWidget(self.widget_1)
        self.deom_list.setMinimumSize(QtCore.QSize(300, 405))
        self.deom_list.setMaximumSize(QtCore.QSize(300, 405))
        self.deom_list.setStyleSheet("QListWidget {\n"
"    background-color: gray;  /* 設定背景顏色為灰色 */\n"
"    border-radius: 15px;     /* 設定邊角圓滑，數值越大越圓 */\n"
"    color: white;            /* 設定文字顏色為白色 */\n"
"    font-size: 15px;         /* 設定字體大小為 15px */\n"
"    text-align: center;      /* 水平置中，Qt 不支援此屬性 */\n"
"    qproperty-alignment: AlignCenter;  /* Qt 標準方式設定文字置中 */\n"
"}\n"
"")
        self.deom_list.setObjectName("deom_list")
        self.horizontalLayout_8.addWidget(self.deom_list)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.widget_1)
        self.widget_3.setMinimumSize(QtCore.QSize(711, 311))
        self.widget_3.setMaximumSize(QtCore.QSize(711, 311))
        self.widget_3.setObjectName("widget_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 220, 51, 51))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setMouseTracking(False)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: none;               /* 取消邊框 */\n"
"    border-radius: 25px;        /* 邊角圓滑 */\n"
"    text-align: center;\n"
"    background: #ffffff;       /* 白底 */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #e0e0e0;        /* 淺灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #bdbdbd;        /* 深一點的淺灰色 */\n"
"}\n"
"")
        self.pushButton_5.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-voice-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon13)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.layoutWidget = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 501, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pos_reg_label = QtWidgets.QTextEdit(self.layoutWidget)
        self.pos_reg_label.setMinimumSize(QtCore.QSize(491, 71))
        self.pos_reg_label.setMaximumSize(QtCore.QSize(491, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pos_reg_label.setFont(font)
        self.pos_reg_label.setStyleSheet("QTextEdit {\n"
"    background-color: #E8FFF5;  /* 設定背景顏色為淺黃色 (LemonChiffon) */\n"
"    border-radius: 15px;        /* 設定邊角圓滑，數值越大越圓 */\n"
"    border: 1px solid #D0D0D0;    /* 設定 1px 黑色邊框 */\n"
"    color: black;               /* 可選：設定文字顏色 */\n"
"    qproperty-readOnly: true; \n"
"}\n"
"\n"
"")
        self.pos_reg_label.setObjectName("pos_reg_label")
        self.verticalLayout_9.addWidget(self.pos_reg_label)
        self.gesture_reg_label = QtWidgets.QTextEdit(self.layoutWidget)
        self.gesture_reg_label.setMinimumSize(QtCore.QSize(491, 71))
        self.gesture_reg_label.setMaximumSize(QtCore.QSize(491, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.gesture_reg_label.setFont(font)
        self.gesture_reg_label.setStyleSheet("QTextEdit {\n"
"    background-color: #E8FFF5;  /* 設定背景顏色為淺黃色 (LemonChiffon) */\n"
"    border-radius: 15px;        /* 設定邊角圓滑，數值越大越圓 */\n"
"    border: 1px solid #D0D0D0;    /* 設定 1px 黑色邊框 */\n"
"    color: black;               /* 可選：設定文字顏色 */\n"
"    qproperty-readOnly: true; \n"
"}\n"
"\n"
"")
        self.gesture_reg_label.setObjectName("gesture_reg_label")
        self.verticalLayout_9.addWidget(self.gesture_reg_label)
        self.gesture_reg_label_2 = QtWidgets.QTextEdit(self.layoutWidget)
        self.gesture_reg_label_2.setMinimumSize(QtCore.QSize(491, 101))
        self.gesture_reg_label_2.setMaximumSize(QtCore.QSize(491, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.gesture_reg_label_2.setFont(font)
        self.gesture_reg_label_2.setStyleSheet("QTextEdit {\n"
"    background-color: #E8FFF5;  /* 設定背景顏色為淺黃色 (LemonChiffon) */\n"
"    border-radius: 15px;        /* 設定邊角圓滑，數值越大越圓 */\n"
"    border: 1px solid #D0D0D0;    /* 設定 1px 黑色邊框 */\n"
"    color: black;               /* 可選：設定文字顏色 */\n"
"    qproperty-readOnly: true; \n"
"}\n"
"\n"
"")
        self.gesture_reg_label_2.setObjectName("gesture_reg_label_2")
        self.verticalLayout_9.addWidget(self.gesture_reg_label_2)
        self.horizontalLayout_10.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget_1)
        self.widget_2.setMinimumSize(QtCore.QSize(461, 311))
        self.widget_2.setMaximumSize(QtCore.QSize(461, 311))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.timer_label = QtWidgets.QLabel(self.widget_2)
        self.timer_label.setMinimumSize(QtCore.QSize(431, 171))
        self.timer_label.setMaximumSize(QtCore.QSize(431, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.timer_label.setFont(font)
        self.timer_label.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #e1f5fe, stop:1 #b3e5fc); /* 稍微深一點的藍色 */\n"
"    color: black;               /* 文字顏色為黑色 */\n"
"    border-radius: 10px;        /* 邊角圓滑 */\n"
"    padding: 5px;               /* 內邊距，讓文字不會緊貼邊緣 */\n"
"    qproperty-alignment: AlignCenter;  /* 文字置中 */\n"
"    border: 2px solid #90caf9;  /* 細邊框，顏色為淡藍色 */\n"
"}\n"
"")
        self.timer_label.setObjectName("timer_label")
        self.verticalLayout_10.addWidget(self.timer_label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.set_time_btn = QtWidgets.QPushButton(self.widget_2)
        self.set_time_btn.setMinimumSize(QtCore.QSize(121, 61))
        self.set_time_btn.setMaximumSize(QtCore.QSize(121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.set_time_btn.setFont(font)
        self.set_time_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.set_time_btn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 25px;\n"
"    text-align: center;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* 滑鼠移上去時變成稍微深一點的灰色 */\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #999\n"
"    );\n"
"}\n"
"\n"
"/* 按下時變成更深的灰色 */\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"    );\n"
"}\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-stopwatch-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_time_btn.setIcon(icon14)
        self.set_time_btn.setObjectName("set_time_btn")
        self.horizontalLayout_9.addWidget(self.set_time_btn)
        self.start_btn = QtWidgets.QPushButton(self.widget_2)
        self.start_btn.setMinimumSize(QtCore.QSize(121, 61))
        self.start_btn.setMaximumSize(QtCore.QSize(121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.start_btn.setFont(font)
        self.start_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_btn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #388E3C; /* 綠色邊框 */\n"
"    border-radius: 25px;\n"
"    text-align: center;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #a8e6a3, stop: 1 #4caf50\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* 滑鼠移上去時，顏色介於原按鈕（#4caf50）和按下（#2e7d32）之間 */\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #81c784, stop: 1 #388e3c\n"
"    );\n"
"}\n"
"\n"
"/* 按下時變成最深的顏色 */\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #4caf50, stop: 1 #2e7d32\n"
"    );\n"
"}\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-start-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_btn.setIcon(icon15)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_9.addWidget(self.start_btn)
        self.rst_btn = QtWidgets.QPushButton(self.widget_2)
        self.rst_btn.setMinimumSize(QtCore.QSize(121, 61))
        self.rst_btn.setMaximumSize(QtCore.QSize(121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rst_btn.setFont(font)
        self.rst_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rst_btn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #d32f2f; /* 紅色邊框 */\n"
"    border-radius: 25px;\n"
"    text-align: center;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #f28b82, stop: 1 #d32f2f\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* 滑鼠移上去時，顏色介於原按鈕（#d32f2f）和按下（#b71c1c）之間 */\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e57373, stop: 1 #c62828\n"
"    );\n"
"}\n"
"\n"
"/* 按下時變成最深的顏色 */\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #d32f2f, stop: 1 #b71c1c\n"
"    );\n"
"}\n"
"")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-reset-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rst_btn.setIcon(icon16)
        self.rst_btn.setObjectName("rst_btn")
        self.horizontalLayout_9.addWidget(self.rst_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_1)
        self.widget.setMinimumSize(QtCore.QSize(311, 311))
        self.widget.setMaximumSize(QtCore.QSize(311, 311))
        self.widget.setStyleSheet("QWidget {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #e1f5fe, stop:1 #b3e5fc); /* 稍微深一點的藍色 */\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    padding: 4px 15px;\n"
"}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(171, 51))
        self.pushButton.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #0288d1; /* 藍色邊框 */\n"
"    border-radius: 25px;\n"
"    border-style: outset;\n"
"    text-align: left;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #81d4fa, stop: 1 #0288d1\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #4fc3f7, stop: 1 #0277bd\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #0288d1, stop: 1 #01579b\n"
"    );\n"
"}\n"
"")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-1-key-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon17)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(171, 51))
        self.pushButton_2.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #388E3C; /* 綠色邊框 */\n"
"    border-radius: 25px;\n"
"    border-style: outset;\n"
"    text-align: left;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #a8e6a3, stop: 1 #4caf50\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #81c784, stop: 1 #388e3c\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #4caf50, stop: 1 #2e7d32\n"
"    );\n"
"}\n"
"\n"
"")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-2-key-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon18)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(171, 51))
        self.pushButton_3.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #f57c00; /* 橘色邊框 */\n"
"    border-radius: 25px;\n"
"    border-style: outset;\n"
"    text-align: left;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffcc80, stop: 1 #f57c00\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffb74d, stop: 1 #ef6c00\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #f57c00, stop: 1 #e65100\n"
"    );\n"
"}\n"
"")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-3-key-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon19)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(171, 51))
        self.pushButton_4.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #d32f2f; /* 紅色邊框 */\n"
"    border-radius: 25px;\n"
"    border-style: outset;\n"
"    text-align: left;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #f28b82, stop: 1 #d32f2f\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e57373, stop: 1 #c62828\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #d32f2f, stop: 1 #b71c1c\n"
"    );\n"
"}\n"
"")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-4-key-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon20)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.widget)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_12.addWidget(self.widget_1)
        self.stackedWidget.addWidget(self.home_page)
        self.music_page = QtWidgets.QWidget()
        self.music_page.setObjectName("music_page")
        self.label_2 = QtWidgets.QLabel(self.music_page)
        self.label_2.setGeometry(QtCore.QRect(400, 200, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.music_page)
        self.progress_page = QtWidgets.QWidget()
        self.progress_page.setObjectName("progress_page")
        self.label_3 = QtWidgets.QLabel(self.progress_page)
        self.label_3.setGeometry(QtCore.QRect(460, 260, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.progress_page)
        self.share_page = QtWidgets.QWidget()
        self.share_page.setObjectName("share_page")
        self.label_4 = QtWidgets.QLabel(self.share_page)
        self.label_4.setGeometry(QtCore.QRect(480, 250, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.share_page)
        self.account_page = QtWidgets.QWidget()
        self.account_page.setObjectName("account_page")
        self.label_6 = QtWidgets.QLabel(self.account_page)
        self.label_6.setGeometry(QtCore.QRect(310, 240, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.account_page)
        self.info_page = QtWidgets.QWidget()
        self.info_page.setObjectName("info_page")
        self.label_5 = QtWidgets.QLabel(self.info_page)
        self.label_5.setGeometry(QtCore.QRect(420, 280, 137, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.info_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.verticalLayout_7.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.menu_btn.toggled['bool'].connect(self.icon_only_frame.setHidden) # type: ignore
        self.menu_btn.toggled['bool'].connect(self.full_menu_frame.setVisible) # type: ignore
        self.home_btn.toggled['bool'].connect(self.full_home_btn.setChecked) # type: ignore
        self.music_btn.toggled['bool'].connect(self.full_music_btn.setChecked) # type: ignore
        self.progress_btn.toggled['bool'].connect(self.full_progress_btn.setChecked) # type: ignore
        self.share_btn.toggled['bool'].connect(self.full_share_btn.setChecked) # type: ignore
        self.account_btn.toggled['bool'].connect(self.full_account_btn.setChecked) # type: ignore
        self.full_home_btn.toggled['bool'].connect(self.home_btn.setChecked) # type: ignore
        self.full_music_btn.toggled['bool'].connect(self.music_btn.setChecked) # type: ignore
        self.full_progress_btn.toggled['bool'].connect(self.progress_btn.setChecked) # type: ignore
        self.full_share_btn.toggled['bool'].connect(self.share_btn.setChecked) # type: ignore
        self.full_account_btn.toggled['bool'].connect(self.account_btn.setChecked) # type: ignore
        self.info_btn.toggled['bool'].connect(self.full_info_btn.setChecked) # type: ignore
        self.full_info_btn.toggled['bool'].connect(self.info_btn.setChecked) # type: ignore
        self.login_out_btn.toggled['bool'].connect(self.full_login_out_btn.setChecked) # type: ignore
        self.full_login_out_btn.toggled['bool'].connect(self.login_out_btn.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "AI  Yoga  Coach"))
        self.full_home_btn.setText(_translate("MainWindow", "Home"))
        self.full_music_btn.setText(_translate("MainWindow", "Music"))
        self.full_progress_btn.setText(_translate("MainWindow", "Progress"))
        self.full_share_btn.setText(_translate("MainWindow", "Share"))
        self.full_account_btn.setText(_translate("MainWindow", "Account"))
        self.full_info_btn.setText(_translate("MainWindow", "Information"))
        self.full_login_out_btn.setText(_translate("MainWindow", "Log In/Out"))
        self.account_status_label.setText(_translate("MainWindow", "Visitor"))
        self.camera_label.setText(_translate("MainWindow", "Lens screen not found"))
        self.demo_label.setText(_translate("MainWindow", "Demo"))
        self.pos_reg_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">姿勢辨識</p></body></html>"))
        self.gesture_reg_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">手勢辨識</p></body></html>"))
        self.gesture_reg_label_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">建議</p></body></html>"))
        self.timer_label.setText(_translate("MainWindow", "00:00.00"))
        self.set_time_btn.setText(_translate("MainWindow", "Set Time"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.rst_btn.setText(_translate("MainWindow", "Reset"))
        self.label.setText(_translate("MainWindow", "Mode Selection: "))
        self.pushButton.setText(_translate("MainWindow", " PRACTICE"))
        self.pushButton_2.setText(_translate("MainWindow", " EASY"))
        self.pushButton_3.setText(_translate("MainWindow", " NORMAL"))
        self.pushButton_4.setText(_translate("MainWindow", " HARD"))
        self.label_2.setText(_translate("MainWindow", "Music Page"))
        self.label_3.setText(_translate("MainWindow", "Progress Page"))
        self.label_4.setText(_translate("MainWindow", "Share Page"))
        self.label_6.setText(_translate("MainWindow", "Account Page"))
        self.label_5.setText(_translate("MainWindow", "Info Page"))
import resource_rc
