# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lolJames\OneDrive\桌面\AI Yoga Coach\AIYogaCoachInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1687, 842)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/yoga-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#title_frame {\n"
"    border-top-left-radius: 10px;\n"
"    background-color: rgb(170, 255, 255);\n"
"}\n"
"\n"
"#main_frame {\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                            stop:0 #E3F2FD, stop:1 #BBDEFB);\n"
"}\n"
"\n"
"#icon_label {\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"    max-height: 30px;\n"
"    max-width: 30px;\n"
"}\n"
"\n"
"#title_frame QPushButton {\n"
"    border: none;\n"
"    width: 50px;\n"
"    height: 40px;\n"
"}\n"
"\n"
"#maximize_btn:hover, #minimize_btn:hover {\n"
"background-color:  #BBDEFB;\n"
"}\n"
"\n"
"#close_btn:hover {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"#close_btn, #title_frame {\n"
"    border-top-right-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_label = QtWidgets.QLabel(self.title_frame)
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap(":/icons/icons/yoga-logo.png"))
        self.icon_label.setObjectName("icon_label")
        self.horizontalLayout_2.addWidget(self.icon_label)
        self.title_label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_2.addWidget(self.title_label)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimize_btn = QtWidgets.QPushButton(self.title_frame)
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-minimize-window-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout.addWidget(self.minimize_btn)
        self.maximize_btn = QtWidgets.QPushButton(self.title_frame)
        self.maximize_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-full-screen-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximize_btn.setIcon(icon2)
        self.maximize_btn.setObjectName("maximize_btn")
        self.horizontalLayout.addWidget(self.maximize_btn)
        self.close_btn = QtWidgets.QPushButton(self.title_frame)
        self.close_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-close-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon3)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.title_frame)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.icon_only_frame = QtWidgets.QFrame(self.main_frame)
        self.icon_only_frame.setStyleSheet("    #icon_only_frame {\n"
"        background-color: #b1dcef;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    #icon_only_frame QPushButton {\n"
"        height:50px;\n"
"        border:none;\n"
"    }\n"
"\n"
"    #icon_only_frame QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }")
        self.icon_only_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_only_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_only_frame.setObjectName("icon_only_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.icon_only_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.home_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-home-page-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon4)
        self.home_btn.setIconSize(QtCore.QSize(30, 30))
        self.home_btn.setCheckable(True)
        self.home_btn.setAutoExclusive(True)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout.addWidget(self.home_btn)
        self.music_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.music_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-musical-note-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.music_btn.setIcon(icon5)
        self.music_btn.setIconSize(QtCore.QSize(30, 30))
        self.music_btn.setCheckable(True)
        self.music_btn.setAutoExclusive(True)
        self.music_btn.setObjectName("music_btn")
        self.verticalLayout.addWidget(self.music_btn)
        self.progress_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.progress_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-chart-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.progress_btn.setIcon(icon6)
        self.progress_btn.setIconSize(QtCore.QSize(30, 30))
        self.progress_btn.setCheckable(True)
        self.progress_btn.setAutoExclusive(True)
        self.progress_btn.setObjectName("progress_btn")
        self.verticalLayout.addWidget(self.progress_btn)
        self.share_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.share_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-share-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.share_btn.setIcon(icon7)
        self.share_btn.setIconSize(QtCore.QSize(30, 30))
        self.share_btn.setCheckable(True)
        self.share_btn.setAutoExclusive(True)
        self.share_btn.setObjectName("share_btn")
        self.verticalLayout.addWidget(self.share_btn)
        self.account_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.account_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-account-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.account_btn.setIcon(icon8)
        self.account_btn.setIconSize(QtCore.QSize(30, 30))
        self.account_btn.setCheckable(True)
        self.account_btn.setAutoExclusive(True)
        self.account_btn.setObjectName("account_btn")
        self.verticalLayout.addWidget(self.account_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.info_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-info-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_btn.setIcon(icon9)
        self.info_btn.setIconSize(QtCore.QSize(30, 30))
        self.info_btn.setCheckable(True)
        self.info_btn.setAutoExclusive(True)
        self.info_btn.setObjectName("info_btn")
        self.verticalLayout_2.addWidget(self.info_btn)
        self.login_out_btn = QtWidgets.QPushButton(self.icon_only_frame)
        self.login_out_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-logout-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_out_btn.setIcon(icon10)
        self.login_out_btn.setIconSize(QtCore.QSize(30, 30))
        self.login_out_btn.setCheckable(False)
        self.login_out_btn.setAutoExclusive(False)
        self.login_out_btn.setObjectName("login_out_btn")
        self.verticalLayout_2.addWidget(self.login_out_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addWidget(self.icon_only_frame)
        self.full_menu_frame = QtWidgets.QFrame(self.main_frame)
        self.full_menu_frame.setStyleSheet("\n"
"    #full_menu_frame {\n"
"        background-color:  #b1dcef;\n"
"    }\n"
"\n"
"    /* style for QPushButton */\n"
"    #full_menu_frame QPushButton {\n"
"        border:none;\n"
"        height: 50px;\n"
"        text-align: left;\n"
"    }\n"
"\n"
"    #full_menu_frame QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"\n"
"    #full_menu_frame QPushButton:checked {\n"
"        color: #fff;\n"
"    }")
        self.full_menu_frame.setObjectName("full_menu_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.full_menu_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.full_home_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_home_btn.setFont(font)
        self.full_home_btn.setIcon(icon4)
        self.full_home_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_home_btn.setCheckable(True)
        self.full_home_btn.setAutoExclusive(True)
        self.full_home_btn.setObjectName("full_home_btn")
        self.verticalLayout_3.addWidget(self.full_home_btn)
        self.full_music_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_music_btn.setFont(font)
        self.full_music_btn.setIcon(icon5)
        self.full_music_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_music_btn.setCheckable(True)
        self.full_music_btn.setAutoExclusive(True)
        self.full_music_btn.setObjectName("full_music_btn")
        self.verticalLayout_3.addWidget(self.full_music_btn)
        self.full_progress_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_progress_btn.setFont(font)
        self.full_progress_btn.setIcon(icon6)
        self.full_progress_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_progress_btn.setCheckable(True)
        self.full_progress_btn.setAutoExclusive(True)
        self.full_progress_btn.setObjectName("full_progress_btn")
        self.verticalLayout_3.addWidget(self.full_progress_btn)
        self.full_share_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_share_btn.setFont(font)
        self.full_share_btn.setIcon(icon7)
        self.full_share_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_share_btn.setCheckable(True)
        self.full_share_btn.setAutoExclusive(True)
        self.full_share_btn.setObjectName("full_share_btn")
        self.verticalLayout_3.addWidget(self.full_share_btn)
        self.full_account_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_account_btn.setFont(font)
        self.full_account_btn.setIcon(icon8)
        self.full_account_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_account_btn.setCheckable(True)
        self.full_account_btn.setAutoExclusive(True)
        self.full_account_btn.setObjectName("full_account_btn")
        self.verticalLayout_3.addWidget(self.full_account_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.full_info_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_info_btn.setFont(font)
        self.full_info_btn.setIcon(icon9)
        self.full_info_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_info_btn.setCheckable(True)
        self.full_info_btn.setAutoExclusive(True)
        self.full_info_btn.setObjectName("full_info_btn")
        self.verticalLayout_4.addWidget(self.full_info_btn)
        self.full_login_out_btn = QtWidgets.QPushButton(self.full_menu_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.full_login_out_btn.setFont(font)
        self.full_login_out_btn.setIcon(icon10)
        self.full_login_out_btn.setIconSize(QtCore.QSize(30, 30))
        self.full_login_out_btn.setCheckable(False)
        self.full_login_out_btn.setAutoExclusive(False)
        self.full_login_out_btn.setObjectName("full_login_out_btn")
        self.verticalLayout_4.addWidget(self.full_login_out_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addWidget(self.full_menu_frame)
        self.frame_3 = QtWidgets.QFrame(self.main_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setStyleSheet("QWidget {\n"
"    background-color: #D1E9E9; /* 淺綠色 */\n"
"}\n"
"")
        self.home_page.setObjectName("home_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_1 = QtWidgets.QWidget(self.home_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(sizePolicy)
        self.widget_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget_1.setObjectName("widget_1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.camera_label = QtWidgets.QLabel(self.widget_1)
        self.camera_label.setMinimumSize(QtCore.QSize(720, 405))
        self.camera_label.setMaximumSize(QtCore.QSize(720, 405))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.camera_label.setFont(font)
        self.camera_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camera_label.setStyleSheet("QLabel {\n"
"    background-color: gray;  /* 設定背景顏色為灰色 */\n"
"    border-radius: 15px;     /* 設定邊角圓滑，數值越大越圓 */\n"
"    color: white;            /* 設定文字顏色為白色，讓字更清楚 */\n"
"    text-align: center;      /* 水平置中，Qt 不支援此屬性，要用對齊方式 */\n"
"    qproperty-alignment: AlignCenter;  /* Qt 標準方式設定文字置中 */\n"
"}\n"
"")
        self.camera_label.setObjectName("camera_label")
        self.horizontalLayout_8.addWidget(self.camera_label)
        self.demo_label = QtWidgets.QLabel(self.widget_1)
        self.demo_label.setMinimumSize(QtCore.QSize(440, 405))
        self.demo_label.setMaximumSize(QtCore.QSize(400, 405))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.demo_label.setFont(font)
        self.demo_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.demo_label.setStyleSheet("QLabel {\n"
"    background-color: gray;  /* 設定背景顏色為灰色 */\n"
"    border-radius: 15px;     /* 設定邊角圓滑，數值越大越圓 */\n"
"    color: white;            /* 設定文字顏色為白色，讓字更清楚 */\n"
"    text-align: center;      /* 水平置中，Qt 不支援此屬性，要用對齊方式 */\n"
"    qproperty-alignment: AlignCenter;  /* Qt 標準方式設定文字置中 */\n"
"}\n"
"")
        self.demo_label.setObjectName("demo_label")
        self.horizontalLayout_8.addWidget(self.demo_label)
        self.demo_list = QtWidgets.QListWidget(self.widget_1)
        self.demo_list.setMinimumSize(QtCore.QSize(300, 405))
        self.demo_list.setMaximumSize(QtCore.QSize(300, 405))
        self.demo_list.setStyleSheet("QListWidget {\n"
"    background-color: gray;  /* 設定背景顏色為灰色 */\n"
"    border-radius: 15px;     /* 設定邊角圓滑，數值越大越圓 */\n"
"    color: white;            /* 設定文字顏色為白色 */\n"
"    font-size: 15px;         /* 設定字體大小為 15px */\n"
"    text-align: center;      /* 水平置中，Qt 不支援此屬性 */\n"
"    qproperty-alignment: AlignCenter;  /* Qt 標準方式設定文字置中 */\n"
"}\n"
"")
        self.demo_list.setObjectName("demo_list")
        self.horizontalLayout_8.addWidget(self.demo_list)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.widget_1)
        self.widget_3.setMinimumSize(QtCore.QSize(711, 311))
        self.widget_3.setMaximumSize(QtCore.QSize(711, 311))
        self.widget_3.setObjectName("widget_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 220, 51, 51))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setMouseTracking(False)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: none;               /* 取消邊框 */\n"
"    border-radius: 25px;        /* 邊角圓滑 */\n"
"    text-align: center;\n"
"    background: #ffffff;       /* 白底 */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #e0e0e0;        /* 淺灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #bdbdbd;        /* 深一點的淺灰色 */\n"
"}\n"
"")
        self.pushButton_5.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-voice-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon11)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.layoutWidget = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 501, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pos_reg_label = QtWidgets.QTextEdit(self.layoutWidget)
        self.pos_reg_label.setMinimumSize(QtCore.QSize(491, 71))
        self.pos_reg_label.setMaximumSize(QtCore.QSize(491, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pos_reg_label.setFont(font)
        self.pos_reg_label.setStyleSheet("QTextEdit {\n"
"    background-color: #E8FFF5;  /* 設定背景顏色為淺黃色 (LemonChiffon) */\n"
"    border-radius: 15px;        /* 設定邊角圓滑，數值越大越圓 */\n"
"    border: 1px solid #D0D0D0;    /* 設定 1px 黑色邊框 */\n"
"    color: black;               /* 可選：設定文字顏色 */\n"
"    qproperty-readOnly: true; \n"
"}\n"
"\n"
"")
        self.pos_reg_label.setObjectName("pos_reg_label")
        self.verticalLayout_9.addWidget(self.pos_reg_label)
        self.gesture_reg_label = QtWidgets.QTextEdit(self.layoutWidget)
        self.gesture_reg_label.setMinimumSize(QtCore.QSize(491, 71))
        self.gesture_reg_label.setMaximumSize(QtCore.QSize(491, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.gesture_reg_label.setFont(font)
        self.gesture_reg_label.setStyleSheet("QTextEdit {\n"
"    background-color: #E8FFF5;  /* 設定背景顏色為淺黃色 (LemonChiffon) */\n"
"    border-radius: 15px;        /* 設定邊角圓滑，數值越大越圓 */\n"
"    border: 1px solid #D0D0D0;    /* 設定 1px 黑色邊框 */\n"
"    color: black;               /* 可選：設定文字顏色 */\n"
"    qproperty-readOnly: true; \n"
"}\n"
"\n"
"")
        self.gesture_reg_label.setObjectName("gesture_reg_label")
        self.verticalLayout_9.addWidget(self.gesture_reg_label)
        self.gesture_reg_label_2 = QtWidgets.QTextEdit(self.layoutWidget)
        self.gesture_reg_label_2.setMinimumSize(QtCore.QSize(491, 101))
        self.gesture_reg_label_2.setMaximumSize(QtCore.QSize(491, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.gesture_reg_label_2.setFont(font)
        self.gesture_reg_label_2.setStyleSheet("QTextEdit {\n"
"    background-color: #E8FFF5;  /* 設定背景顏色為淺黃色 (LemonChiffon) */\n"
"    border-radius: 15px;        /* 設定邊角圓滑，數值越大越圓 */\n"
"    border: 1px solid #D0D0D0;    /* 設定 1px 黑色邊框 */\n"
"    color: black;               /* 可選：設定文字顏色 */\n"
"    qproperty-readOnly: true; \n"
"}\n"
"\n"
"")
        self.gesture_reg_label_2.setObjectName("gesture_reg_label_2")
        self.verticalLayout_9.addWidget(self.gesture_reg_label_2)
        self.horizontalLayout_10.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget_1)
        self.widget_2.setMinimumSize(QtCore.QSize(461, 311))
        self.widget_2.setMaximumSize(QtCore.QSize(461, 311))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.timer_label = QtWidgets.QLabel(self.widget_2)
        self.timer_label.setMinimumSize(QtCore.QSize(431, 171))
        self.timer_label.setMaximumSize(QtCore.QSize(431, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.timer_label.setFont(font)
        self.timer_label.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #e1f5fe, stop:1 #b3e5fc); /* 稍微深一點的藍色 */\n"
"    color: black;               /* 文字顏色為黑色 */\n"
"    border-radius: 10px;        /* 邊角圓滑 */\n"
"    padding: 5px;               /* 內邊距，讓文字不會緊貼邊緣 */\n"
"    qproperty-alignment: AlignCenter;  /* 文字置中 */\n"
"    border: 2px solid #90caf9;  /* 細邊框，顏色為淡藍色 */\n"
"}\n"
"")
        self.timer_label.setObjectName("timer_label")
        self.verticalLayout_10.addWidget(self.timer_label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.set_time_btn = QtWidgets.QPushButton(self.widget_2)
        self.set_time_btn.setMinimumSize(QtCore.QSize(121, 61))
        self.set_time_btn.setMaximumSize(QtCore.QSize(121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.set_time_btn.setFont(font)
        self.set_time_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.set_time_btn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 25px;\n"
"    text-align: center;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* 滑鼠移上去時變成稍微深一點的灰色 */\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #999\n"
"    );\n"
"}\n"
"\n"
"/* 按下時變成更深的灰色 */\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"    );\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-stopwatch-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_time_btn.setIcon(icon12)
        self.set_time_btn.setObjectName("set_time_btn")
        self.horizontalLayout_9.addWidget(self.set_time_btn)
        self.start_btn = QtWidgets.QPushButton(self.widget_2)
        self.start_btn.setMinimumSize(QtCore.QSize(121, 61))
        self.start_btn.setMaximumSize(QtCore.QSize(121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.start_btn.setFont(font)
        self.start_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_btn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #388E3C; /* 綠色邊框 */\n"
"    border-radius: 25px;\n"
"    text-align: center;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #a8e6a3, stop: 1 #4caf50\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* 滑鼠移上去時，顏色介於原按鈕（#4caf50）和按下（#2e7d32）之間 */\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #81c784, stop: 1 #388e3c\n"
"    );\n"
"}\n"
"\n"
"/* 按下時變成最深的顏色 */\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #4caf50, stop: 1 #2e7d32\n"
"    );\n"
"}\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-start-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_btn.setIcon(icon13)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_9.addWidget(self.start_btn)
        self.rst_btn = QtWidgets.QPushButton(self.widget_2)
        self.rst_btn.setMinimumSize(QtCore.QSize(121, 61))
        self.rst_btn.setMaximumSize(QtCore.QSize(121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rst_btn.setFont(font)
        self.rst_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rst_btn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #d32f2f; /* 紅色邊框 */\n"
"    border-radius: 25px;\n"
"    text-align: center;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #f28b82, stop: 1 #d32f2f\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* 滑鼠移上去時，顏色介於原按鈕（#d32f2f）和按下（#b71c1c）之間 */\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e57373, stop: 1 #c62828\n"
"    );\n"
"}\n"
"\n"
"/* 按下時變成最深的顏色 */\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #d32f2f, stop: 1 #b71c1c\n"
"    );\n"
"}\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-reset-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rst_btn.setIcon(icon14)
        self.rst_btn.setObjectName("rst_btn")
        self.horizontalLayout_9.addWidget(self.rst_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_1)
        self.widget.setMinimumSize(QtCore.QSize(311, 311))
        self.widget.setMaximumSize(QtCore.QSize(311, 311))
        self.widget.setStyleSheet("QWidget {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #e1f5fe, stop:1 #b3e5fc); /* 稍微深一點的藍色 */\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    padding: 4px 15px;\n"
"}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(171, 51))
        self.pushButton.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #0288d1; /* 藍色邊框 */\n"
"    border-radius: 25px;\n"
"    border-style: outset;\n"
"    text-align: left;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #81d4fa, stop: 1 #0288d1\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #4fc3f7, stop: 1 #0277bd\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #0288d1, stop: 1 #01579b\n"
"    );\n"
"}\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-1-key-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon15)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(171, 51))
        self.pushButton_2.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #388E3C; /* 綠色邊框 */\n"
"    border-radius: 25px;\n"
"    border-style: outset;\n"
"    text-align: left;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #a8e6a3, stop: 1 #4caf50\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #81c784, stop: 1 #388e3c\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #4caf50, stop: 1 #2e7d32\n"
"    );\n"
"}\n"
"\n"
"")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-2-key-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon16)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(171, 51))
        self.pushButton_3.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #f57c00; /* 橘色邊框 */\n"
"    border-radius: 25px;\n"
"    border-style: outset;\n"
"    text-align: left;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffcc80, stop: 1 #f57c00\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffb74d, stop: 1 #ef6c00\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #f57c00, stop: 1 #e65100\n"
"    );\n"
"}\n"
"")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-3-key-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon17)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(171, 51))
        self.pushButton_4.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #d32f2f; /* 紅色邊框 */\n"
"    border-radius: 25px;\n"
"    border-style: outset;\n"
"    text-align: left;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #f28b82, stop: 1 #d32f2f\n"
"    );\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e57373, stop: 1 #c62828\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #d32f2f, stop: 1 #b71c1c\n"
"    );\n"
"}\n"
"")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-4-key-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon18)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.widget)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_12.addWidget(self.widget_1)
        self.stackedWidget.addWidget(self.home_page)
        self.music_page = QtWidgets.QWidget()
        self.music_page.setStyleSheet("")
        self.music_page.setObjectName("music_page")
        self.widget_4 = QtWidgets.QWidget(self.music_page)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 1507, 742))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMaximumSize(QtCore.QSize(1507, 742))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.widget_4.setFont(font)
        self.widget_4.setStyleSheet("\\")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_2 = QtWidgets.QFrame(self.widget_4)
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    border: 2px solid #aaa;\n"
"    border-radius: 12px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(61, 41))
        self.label_2.setMaximumSize(QtCore.QSize(61, 41))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/current-music.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setMinimumSize(QtCore.QSize(421, 41))
        self.label_7.setMaximumSize(QtCore.QSize(421, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #8f8f8f")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setMinimumSize(QtCore.QSize(481, 40))
        self.label_8.setMaximumSize(QtCore.QSize(481, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(141, 141, 141);\n"
"padding-left: 15px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.current_song_name_label = QtWidgets.QLabel(self.frame_2)
        self.current_song_name_label.setMinimumSize(QtCore.QSize(481, 31))
        self.current_song_name_label.setMaximumSize(QtCore.QSize(481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.current_song_name_label.setFont(font)
        self.current_song_name_label.setStyleSheet("padding-left: 15px;")
        self.current_song_name_label.setObjectName("current_song_name_label")
        self.verticalLayout_13.addWidget(self.current_song_name_label)
        self.label11 = QtWidgets.QLabel(self.frame_2)
        self.label11.setMinimumSize(QtCore.QSize(481, 40))
        self.label11.setMaximumSize(QtCore.QSize(481, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setStyleSheet("color: rgb(141, 141, 141);\n"
"padding-left: 15px;")
        self.label11.setObjectName("label11")
        self.verticalLayout_13.addWidget(self.label11)
        self.current_song_path_label = QtWidgets.QLabel(self.frame_2)
        self.current_song_path_label.setMinimumSize(QtCore.QSize(481, 31))
        self.current_song_path_label.setMaximumSize(QtCore.QSize(481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.current_song_path_label.setFont(font)
        self.current_song_path_label.setStyleSheet("padding-left: 15px\n"
"")
        self.current_song_path_label.setObjectName("current_song_path_label")
        self.verticalLayout_13.addWidget(self.current_song_path_label)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.add_to_playlist_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_to_playlist_btn.sizePolicy().hasHeightForWidth())
        self.add_to_playlist_btn.setSizePolicy(sizePolicy)
        self.add_to_playlist_btn.setMinimumSize(QtCore.QSize(250, 41))
        self.add_to_playlist_btn.setMaximumSize(QtCore.QSize(250, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.add_to_playlist_btn.setFont(font)
        self.add_to_playlist_btn.setStyleSheet("QPushButton {\n"
"    color: white; /* 白字 */\n"
"    background: #ffa500; /* 橘色底 */\n"
"    border-radius: 20px; /* 圓角 */\n"
"    padding: 10px 20px;\n"
"    font-size: 22px;\n"
"    text-align: left;\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"/* 滑鼠移上去：略深橘 */\n"
"QPushButton:hover {\n"
"    background: #e69500;\n"
"    color: white;\n"
"}\n"
"\n"
"/* 按下時：更深橘 */\n"
"QPushButton:pressed {\n"
"    background: #cc8400;\n"
"    color: white;\n"
"}\n"
"")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/music_list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_playlist_btn.setIcon(icon19)
        self.add_to_playlist_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_to_playlist_btn.setObjectName("add_to_playlist_btn")
        self.horizontalLayout_14.addWidget(self.add_to_playlist_btn)
        self.add_to_fav_btn = QtWidgets.QPushButton(self.frame_2)
        self.add_to_fav_btn.setMinimumSize(QtCore.QSize(250, 41))
        self.add_to_fav_btn.setMaximumSize(QtCore.QSize(250, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.add_to_fav_btn.setFont(font)
        self.add_to_fav_btn.setStyleSheet("QPushButton {\n"
"    color: #ff69b4; /* 粉紅字 */\n"
"    background: #ffffff; /* 白底 */\n"
"    border-radius: 20px; /* 圓角 */\n"
"    padding: 10px 20px; /* 增加內邊距 */\n"
"    font-size: 22px;\n"
"    text-align: left; /* 字體靠左 */\n"
"    padding-left: 20px; /* 加一點左邊空間 */\n"
"}\n"
"\n"
"/* 滑鼠移上去：灰底粉紅字 */\n"
"QPushButton:hover {\n"
"    background: #cccccc;\n"
"    color: #ff69b4;\n"
"}\n"
"\n"
"/* 按下時：深灰底粉紅字 */\n"
"QPushButton:pressed {\n"
"    background: #888888;\n"
"    color: #ff69b4;\n"
"}\n"
"")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/icons/like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_fav_btn.setIcon(icon20)
        self.add_to_fav_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_to_fav_btn.setObjectName("add_to_fav_btn")
        self.horizontalLayout_14.addWidget(self.add_to_fav_btn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_17.addWidget(self.frame_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem3)
        self.frame_4 = QtWidgets.QFrame(self.widget_4)
        self.frame_4.setStyleSheet("#frame_4 {\n"
"    background-color: rgb(217, 248, 255);\n"
"    border-radius:12px;\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(40, 40))
        self.label_9.setMaximumSize(QtCore.QSize(40, 40))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/icons/icons/icons8-voice-50.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setMinimumSize(QtCore.QSize(131, 41))
        self.label_10.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(291, 31))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(291, 31))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999; /* 灰色邊框 */\n"
"    background: rgb(229, 229, 229); /* 灰色底 */\n"
"    margin: 2px 0;\n"
"    border-radius: 11px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgba(0, 255, 127, 100); /* 左側淺綠色 */\n"
"    border-radius: 11px;\n"
"    /* 增加 padding 讓 sub-page 和 groove 匹配 */\n"
"    padding-left: 0;\n"
"    padding-right: 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(255, 200, 50); /* 黃色滑塊 */\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -2px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_12.addWidget(self.horizontalSlider)
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setMinimumSize(QtCore.QSize(48, 41))
        self.label_11.setMaximumSize(QtCore.QSize(48, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.verticalLayout_17.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.widget_4)
        self.frame_5.setStyleSheet("frame_5 {\n"
"background-color:rgb(220, 220, 220)\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.play_btn = QtWidgets.QPushButton(self.frame_5)
        self.play_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.play_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.play_btn.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/icons/pase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_btn.setIcon(icon21)
        self.play_btn.setIconSize(QtCore.QSize(40, 40))
        self.play_btn.setFlat(True)
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout_13.addWidget(self.play_btn)
        self.pause_btn = QtWidgets.QPushButton(self.frame_5)
        self.pause_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.pause_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.pause_btn.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_btn.setIcon(icon22)
        self.pause_btn.setIconSize(QtCore.QSize(40, 40))
        self.pause_btn.setFlat(True)
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout_13.addWidget(self.pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.frame_5)
        self.stop_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.stop_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.stop_btn.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon23)
        self.stop_btn.setIconSize(QtCore.QSize(40, 40))
        self.stop_btn.setFlat(True)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_13.addWidget(self.stop_btn)
        self.previous_btn = QtWidgets.QPushButton(self.frame_5)
        self.previous_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.previous_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.previous_btn.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/icons/pre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_btn.setIcon(icon24)
        self.previous_btn.setIconSize(QtCore.QSize(40, 40))
        self.previous_btn.setFlat(True)
        self.previous_btn.setObjectName("previous_btn")
        self.horizontalLayout_13.addWidget(self.previous_btn)
        self.next_btn = QtWidgets.QPushButton(self.frame_5)
        self.next_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.next_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.next_btn.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icons/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon25)
        self.next_btn.setIconSize(QtCore.QSize(40, 40))
        self.next_btn.setFlat(True)
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_13.addWidget(self.next_btn)
        self.shuffle_songs_btn = QtWidgets.QPushButton(self.frame_5)
        self.shuffle_songs_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.shuffle_songs_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.shuffle_songs_btn.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icons/icons/play-random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffle_songs_btn.setIcon(icon26)
        self.shuffle_songs_btn.setIconSize(QtCore.QSize(40, 40))
        self.shuffle_songs_btn.setFlat(True)
        self.shuffle_songs_btn.setObjectName("shuffle_songs_btn")
        self.horizontalLayout_13.addWidget(self.shuffle_songs_btn)
        self.loop_one_btn = QtWidgets.QPushButton(self.frame_5)
        self.loop_one_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.loop_one_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.loop_one_btn.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icons/icons/loop-one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loop_one_btn.setIcon(icon27)
        self.loop_one_btn.setIconSize(QtCore.QSize(40, 40))
        self.loop_one_btn.setFlat(True)
        self.loop_one_btn.setObjectName("loop_one_btn")
        self.horizontalLayout_13.addWidget(self.loop_one_btn)
        self.verticalLayout_17.addWidget(self.frame_5)
        self.horizontalLayout_19.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_6 = QtWidgets.QFrame(self.widget_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.add_songs_btn = QtWidgets.QPushButton(self.frame_6)
        self.add_songs_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.add_songs_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.add_songs_btn.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icons/icons/addFromLocal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_songs_btn.setIcon(icon28)
        self.add_songs_btn.setIconSize(QtCore.QSize(50, 50))
        self.add_songs_btn.setFlat(True)
        self.add_songs_btn.setObjectName("add_songs_btn")
        self.horizontalLayout_15.addWidget(self.add_songs_btn)
        self.remove_selected_btn = QtWidgets.QPushButton(self.frame_6)
        self.remove_selected_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.remove_selected_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.remove_selected_btn.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icons/icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_selected_btn.setIcon(icon29)
        self.remove_selected_btn.setIconSize(QtCore.QSize(50, 50))
        self.remove_selected_btn.setFlat(True)
        self.remove_selected_btn.setObjectName("remove_selected_btn")
        self.horizontalLayout_15.addWidget(self.remove_selected_btn)
        self.clear_all_btn = QtWidgets.QPushButton(self.frame_6)
        self.clear_all_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.clear_all_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.clear_all_btn.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icons/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_all_btn.setIcon(icon30)
        self.clear_all_btn.setIconSize(QtCore.QSize(50, 50))
        self.clear_all_btn.setFlat(True)
        self.clear_all_btn.setObjectName("clear_all_btn")
        self.horizontalLayout_15.addWidget(self.clear_all_btn)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.song_listWidget = QtWidgets.QListWidget(self.frame_6)
        self.song_listWidget.setStyleSheet("color: rgb(86, 227, 194);\n"
"background-color: rgba(0, 0, 0, 100);\n"
"\n"
"selection-background-color: rgb(255, 140, 64);\n"
"selection-color: rgb(255, 255, 255);\n"
"padding:10px;\n"
"border-radius: 20px")
        self.song_listWidget.setObjectName("song_listWidget")
        self.verticalLayout_15.addWidget(self.song_listWidget)
        self.verticalLayout_18.addWidget(self.frame_6)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.songlist_btn = QtWidgets.QPushButton(self.widget_4)
        self.songlist_btn.setMinimumSize(QtCore.QSize(251, 51))
        self.songlist_btn.setMaximumSize(QtCore.QSize(251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.songlist_btn.setFont(font)
        self.songlist_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFD700; /* 黃色 */\n"
"    border: 2px solid #FFC107; /* 深黃色邊框 */\n"
"    border-radius: 25px; /* 膠囊型圓角 */\n"
"    color: white; /* 文字顏色為白色 */\n"
"    padding: 0 30px; /* 左右邊距，保證文本不會緊貼邊框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFCC00; /* 滑鼠移上去時，顏色變淺一點 */\n"
"    border-color: #FFB300; /* 邊框顏色變為稍微深一點的黃色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFB300; /* 按下時，顏色變為更深的黃色 */\n"
"    border-color: #FF9900; /* 邊框顏色更深 */\n"
"}\n"
"")
        self.songlist_btn.setObjectName("songlist_btn")
        self.horizontalLayout_17.addWidget(self.songlist_btn)
        self.playlist_btn = QtWidgets.QPushButton(self.widget_4)
        self.playlist_btn.setMinimumSize(QtCore.QSize(251, 51))
        self.playlist_btn.setMaximumSize(QtCore.QSize(251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.playlist_btn.setFont(font)
        self.playlist_btn.setStyleSheet("QPushButton {\n"
"    background-color: #28a745; /* 綠色 */\n"
"    border: 2px solid #218838; /* 深綠色邊框 */\n"
"    border-radius: 25px; /* 膠囊型圓角 */\n"
"    color: white; /* 文字顏色為白色 */\n"
"    padding: 0 30px; /* 左右邊距，保證文本不會緊貼邊框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #34d058; /* 滑鼠移上去時，顏色變淺一點 */\n"
"    border-color: #2a9d43; /* 邊框顏色變為稍微深一點的綠色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #238636; /* 按下時，顏色變為更深的綠色 */\n"
"    border-color: #1e7e34; /* 邊框顏色更深 */\n"
"}\n"
"")
        self.playlist_btn.setObjectName("playlist_btn")
        self.horizontalLayout_17.addWidget(self.playlist_btn)
        self.favourites_btn = QtWidgets.QPushButton(self.widget_4)
        self.favourites_btn.setMinimumSize(QtCore.QSize(251, 51))
        self.favourites_btn.setMaximumSize(QtCore.QSize(251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.favourites_btn.setFont(font)
        self.favourites_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ff69b4; /* 粉紅色 */\n"
"    border: 2px solid #ff4f9d; /* 深粉紅色邊框 */\n"
"    border-radius: 25px; /* 膠囊型圓角 */\n"
"    color: white; /* 文字顏色為白色 */\n"
"    padding: 0 30px; /* 左右邊距，保證文本不會緊貼邊框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff80bf; /* 滑鼠移上去時，顏色變淺一點 */\n"
"    border-color: #ff66b3; /* 邊框顏色變為稍微深一點的粉紅色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e64a8b; /* 按下時，顏色變為更深的粉紅色 */\n"
"    border-color: #d6336c; /* 邊框顏色更深 */\n"
"}\n"
"")
        self.favourites_btn.setObjectName("favourites_btn")
        self.horizontalLayout_17.addWidget(self.favourites_btn)
        self.verticalLayout_18.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.music_slider = QtWidgets.QSlider(self.widget_4)
        self.music_slider.setMinimumSize(QtCore.QSize(651, 35))
        self.music_slider.setMaximumSize(QtCore.QSize(651, 35))
        self.music_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999; /* 灰色邊框 */\n"
"    background: #cccccc; /* 灰色底色 */\n"
"    height: 8px; /* 設定底部條形的高度 */\n"
"    border-radius: 4px; /* 圓角效果 */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #1db954; /* 綠色進度條 */\n"
"    border-radius: 4px; /* 確保進度條和底部條形有一致的圓角 */\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: white; /* 白色圓點 */\n"
"    border: 2px solid #1db954; /* 綠色邊框 */\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px; /* 圓形圓點 */\n"
"    margin: -6px 0; /* 確保圓點正確對齊 */\n"
"}\n"
"\n"
"QSlider::handle:hover {\n"
"    background: white; /* 滑鼠移到圓點時仍保持白色 */\n"
"    border: 2px solid #1db954; /* 邊框保持綠色 */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"    background: #cccccc; /* 禁用狀態下，進度條顯示灰色 */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"    background: #aaaaaa; /* 禁用狀態下，圓點顏色變成灰色 */\n"
"    border: 2px solid #aaaaaa; /* 圓點邊框顏色變灰 */\n"
"}\n"
"")
        self.music_slider.setOrientation(QtCore.Qt.Horizontal)
        self.music_slider.setObjectName("music_slider")
        self.horizontalLayout_18.addWidget(self.music_slider)
        self.time_label = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(221)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        self.time_label.setMinimumSize(QtCore.QSize(221, 35))
        self.time_label.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("padding:2px;\n"
"border-radius:5px")
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_18.addWidget(self.time_label)
        self.verticalLayout_18.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_18)
        self.stackedWidget.addWidget(self.music_page)
        self.progress_page = QtWidgets.QWidget()
        self.progress_page.setObjectName("progress_page")
        self.label_3 = QtWidgets.QLabel(self.progress_page)
        self.label_3.setGeometry(QtCore.QRect(460, 260, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.progress_page)
        self.share_page = QtWidgets.QWidget()
        self.share_page.setObjectName("share_page")
        self.label_4 = QtWidgets.QLabel(self.share_page)
        self.label_4.setGeometry(QtCore.QRect(480, 250, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.share_page)
        self.account_page = QtWidgets.QWidget()
        self.account_page.setObjectName("account_page")
        self.label_6 = QtWidgets.QLabel(self.account_page)
        self.label_6.setGeometry(QtCore.QRect(310, 240, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.account_page)
        self.info_page = QtWidgets.QWidget()
        self.info_page.setObjectName("info_page")
        self.label_5 = QtWidgets.QLabel(self.info_page)
        self.label_5.setGeometry(QtCore.QRect(420, 280, 137, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.info_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menu_btn = QtWidgets.QPushButton(self.frame)
        self.menu_btn.setStyleSheet("padding: 5px;\n"
"border: none;\n"
"width: 35px;\n"
"height: 35px")
        self.menu_btn.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-hamburger-button-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn.setIcon(icon31)
        self.menu_btn.setIconSize(QtCore.QSize(35, 35))
        self.menu_btn.setCheckable(True)
        self.menu_btn.setAutoExclusive(False)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_6.addWidget(self.menu_btn)
        self.camera_btn = QtWidgets.QPushButton(self.frame)
        self.camera_btn.setEnabled(True)
        self.camera_btn.setStyleSheet("QPushButton {\n"
"    width: 35px;\n"
"    height: 35px;\n"
"    background-color: transparent; \n"
"    border: none;\n"
"    transition: background-color 0.3s ease;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #ff6c7b;\n"
"     border-radius: 5px;\n"
"     border: 1px solid;\n"
"}")
        self.camera_btn.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-camera-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.camera_btn.setIcon(icon32)
        self.camera_btn.setIconSize(QtCore.QSize(35, 35))
        self.camera_btn.setCheckable(True)
        self.camera_btn.setChecked(False)
        self.camera_btn.setObjectName("camera_btn")
        self.horizontalLayout_6.addWidget(self.camera_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.account_status_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.account_status_label.setFont(font)
        self.account_status_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.account_status_label.setObjectName("account_status_label")
        self.horizontalLayout_6.addWidget(self.account_status_label)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.verticalLayout_7.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.menu_btn.toggled['bool'].connect(self.icon_only_frame.setHidden) # type: ignore
        self.menu_btn.toggled['bool'].connect(self.full_menu_frame.setVisible) # type: ignore
        self.home_btn.toggled['bool'].connect(self.full_home_btn.setChecked) # type: ignore
        self.music_btn.toggled['bool'].connect(self.full_music_btn.setChecked) # type: ignore
        self.progress_btn.toggled['bool'].connect(self.full_progress_btn.setChecked) # type: ignore
        self.share_btn.toggled['bool'].connect(self.full_share_btn.setChecked) # type: ignore
        self.account_btn.toggled['bool'].connect(self.full_account_btn.setChecked) # type: ignore
        self.full_home_btn.toggled['bool'].connect(self.home_btn.setChecked) # type: ignore
        self.full_music_btn.toggled['bool'].connect(self.music_btn.setChecked) # type: ignore
        self.full_progress_btn.toggled['bool'].connect(self.progress_btn.setChecked) # type: ignore
        self.full_share_btn.toggled['bool'].connect(self.share_btn.setChecked) # type: ignore
        self.full_account_btn.toggled['bool'].connect(self.account_btn.setChecked) # type: ignore
        self.info_btn.toggled['bool'].connect(self.full_info_btn.setChecked) # type: ignore
        self.full_info_btn.toggled['bool'].connect(self.info_btn.setChecked) # type: ignore
        self.login_out_btn.toggled['bool'].connect(self.full_login_out_btn.setChecked) # type: ignore
        self.full_login_out_btn.toggled['bool'].connect(self.login_out_btn.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "AI  Yoga  Coach"))
        self.full_home_btn.setText(_translate("MainWindow", "Home"))
        self.full_music_btn.setText(_translate("MainWindow", "Music"))
        self.full_progress_btn.setText(_translate("MainWindow", "Progress"))
        self.full_share_btn.setText(_translate("MainWindow", "Share"))
        self.full_account_btn.setText(_translate("MainWindow", "Account"))
        self.full_info_btn.setText(_translate("MainWindow", "Information"))
        self.full_login_out_btn.setText(_translate("MainWindow", "Log In/Out"))
        self.camera_label.setText(_translate("MainWindow", "Lens screen not found"))
        self.demo_label.setText(_translate("MainWindow", "Demo"))
        self.pos_reg_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">姿勢辨識</p></body></html>"))
        self.gesture_reg_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">手勢辨識</p></body></html>"))
        self.gesture_reg_label_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">建議</p></body></html>"))
        self.timer_label.setText(_translate("MainWindow", "00:00.00"))
        self.set_time_btn.setText(_translate("MainWindow", "Set Time"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.rst_btn.setText(_translate("MainWindow", "Reset"))
        self.label.setText(_translate("MainWindow", "Mode Selection: "))
        self.pushButton.setText(_translate("MainWindow", " PRACTICE"))
        self.pushButton_2.setText(_translate("MainWindow", " EASY"))
        self.pushButton_3.setText(_translate("MainWindow", " NORMAL"))
        self.pushButton_4.setText(_translate("MainWindow", " HARD"))
        self.label_7.setText(_translate("MainWindow", "Currently  Playing..."))
        self.label_8.setText(_translate("MainWindow", "Song Name"))
        self.current_song_name_label.setText(_translate("MainWindow", "Song name goes here..."))
        self.label11.setText(_translate("MainWindow", "Song Path"))
        self.current_song_path_label.setText(_translate("MainWindow", "Song path goes here..."))
        self.add_to_playlist_btn.setText(_translate("MainWindow", "Add to Playlist"))
        self.add_to_fav_btn.setText(_translate("MainWindow", "Add to Favourates"))
        self.label_10.setText(_translate("MainWindow", "Volume(%)"))
        self.label_11.setText(_translate("MainWindow", "100"))
        self.label_12.setText(_translate("MainWindow", "Song List"))
        self.songlist_btn.setText(_translate("MainWindow", "Song List"))
        self.playlist_btn.setText(_translate("MainWindow", "Playlists"))
        self.favourites_btn.setText(_translate("MainWindow", "Favourites"))
        self.time_label.setText(_translate("MainWindow", "00:00:00 / 00:00:00"))
        self.label_3.setText(_translate("MainWindow", "Progress Page"))
        self.label_4.setText(_translate("MainWindow", "Share Page"))
        self.label_6.setText(_translate("MainWindow", "Account Page"))
        self.label_5.setText(_translate("MainWindow", "Info Page"))
        self.account_status_label.setText(_translate("MainWindow", "Visitor"))
import resource_rc
