# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\zhuanti\app\AI-Yoga-Coach\comment_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(1)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.comment_area = QtWidgets.QFrame(Frame)
        self.comment_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.comment_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.comment_area.setObjectName("comment_area")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.comment_area)
        self.verticalLayout_48.setSpacing(1)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.user_comment_icon_5 = QtWidgets.QLabel(self.comment_area)
        self.user_comment_icon_5.setMinimumSize(QtCore.QSize(40, 40))
        self.user_comment_icon_5.setText("")
        self.user_comment_icon_5.setObjectName("user_comment_icon_5")
        self.horizontalLayout_78.addWidget(self.user_comment_icon_5)
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.comment_time_5 = QtWidgets.QLabel(self.comment_area)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.comment_time_5.setFont(font)
        self.comment_time_5.setObjectName("comment_time_5")
        self.horizontalLayout_79.addWidget(self.comment_time_5)
        self.comment_name_5 = QtWidgets.QLabel(self.comment_area)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.comment_name_5.setFont(font)
        self.comment_name_5.setObjectName("comment_name_5")
        self.horizontalLayout_79.addWidget(self.comment_name_5)
        self.horizontalLayout_78.addLayout(self.horizontalLayout_79)
        self.horizontalLayout_78.setStretch(0, 1)
        self.horizontalLayout_78.setStretch(1, 5)
        self.verticalLayout_48.addLayout(self.horizontalLayout_78)
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.like_button_5 = QtWidgets.QPushButton(self.comment_area)
        self.like_button_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    icon-size: 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);  /* 半透明黑色遮罩 hover */\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}\n"
"")
        self.like_button_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.like_button_5.setIcon(icon)
        self.like_button_5.setFlat(True)
        self.like_button_5.setObjectName("like_button_5")
        self.horizontalLayout_80.addWidget(self.like_button_5)
        self.like_number_5 = QtWidgets.QLabel(self.comment_area)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setWeight(50)
        self.like_number_5.setFont(font)
        self.like_number_5.setObjectName("like_number_5")
        self.horizontalLayout_80.addWidget(self.like_number_5)
        self.dislike_button_5 = QtWidgets.QPushButton(self.comment_area)
        self.dislike_button_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    icon-size: 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);  /* 半透明黑色遮罩 hover */\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}\n"
"")
        self.dislike_button_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\code\\zhuanti\\app\\AI-Yoga-Coach\\icons/break-heart_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dislike_button_5.setIcon(icon1)
        self.dislike_button_5.setObjectName("dislike_button_5")
        self.horizontalLayout_80.addWidget(self.dislike_button_5)
        self.dislike_number_5 = QtWidgets.QLabel(self.comment_area)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.dislike_number_5.setFont(font)
        self.dislike_number_5.setObjectName("dislike_number_5")
        self.horizontalLayout_80.addWidget(self.dislike_number_5)
        self.verticalLayout_48.addLayout(self.horizontalLayout_80)
        self.comment_text_5 = QtWidgets.QLabel(self.comment_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_text_5.sizePolicy().hasHeightForWidth())
        self.comment_text_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.comment_text_5.setFont(font)
        self.comment_text_5.setWordWrap(True)
        self.comment_text_5.setObjectName("comment_text_5")
        self.verticalLayout_48.addWidget(self.comment_text_5)
        self.verticalLayout_25.addWidget(self.comment_area)
        self.verticalLayout.addLayout(self.verticalLayout_25)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.comment_time_5.setText(_translate("Frame", "2025/04/23"))
        self.comment_name_5.setText(_translate("Frame", "王曉明"))
        self.like_number_5.setText(_translate("Frame", "100"))
        self.dislike_number_5.setText(_translate("Frame", "33"))
        self.comment_text_5.setText(_translate("Frame", "阿囉哈"))
import resource_rc
