# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\zhuanti\app\AI-Yoga-Coach\share_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(448, 647)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem)
        self.share_user_icon = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share_user_icon.sizePolicy().hasHeightForWidth())
        self.share_user_icon.setSizePolicy(sizePolicy)
        self.share_user_icon.setMinimumSize(QtCore.QSize(40, 40))
        self.share_user_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.share_user_icon.setSizeIncrement(QtCore.QSize(0, 0))
        self.share_user_icon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.share_user_icon.setText("")
        self.share_user_icon.setScaledContents(True)
        self.share_user_icon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.share_user_icon.setObjectName("share_user_icon")
        self.horizontalLayout_50.addWidget(self.share_user_icon)
        self.share_user_name = QtWidgets.QLabel(Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.share_user_name.setFont(font)
        self.share_user_name.setText("")
        self.share_user_name.setObjectName("share_user_name")
        self.horizontalLayout_50.addWidget(self.share_user_name)
        self.share_time = QtWidgets.QLabel(Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.share_time.setFont(font)
        self.share_time.setText("")
        self.share_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.share_time.setObjectName("share_time")
        self.horizontalLayout_50.addWidget(self.share_time)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem1)
        self.verticalLayout_24.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem2)
        self.put_picture = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.put_picture.sizePolicy().hasHeightForWidth())
        self.put_picture.setSizePolicy(sizePolicy)
        self.put_picture.setMinimumSize(QtCore.QSize(0, 0))
        self.put_picture.setText("")
        self.put_picture.setScaledContents(True)
        self.put_picture.setObjectName("put_picture")
        self.horizontalLayout_55.addWidget(self.put_picture)
        self.verticalLayout_24.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.put_word = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.put_word.sizePolicy().hasHeightForWidth())
        self.put_word.setSizePolicy(sizePolicy)
        self.put_word.setMaximumSize(QtCore.QSize(448, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.put_word.setFont(font)
        self.put_word.setText("")
        self.put_word.setWordWrap(True)
        self.put_word.setObjectName("put_word")
        self.horizontalLayout_65.addWidget(self.put_word)
        self.verticalLayout_24.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        spacerItem3 = QtWidgets.QSpacerItem(10, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem3)
        self.share_like_btn = QtWidgets.QPushButton(Frame)
        self.share_like_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    icon-size: 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);  /* 半透明黑色遮罩 hover */\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}\n"
"")
        self.share_like_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.share_like_btn.setIcon(icon)
        self.share_like_btn.setIconSize(QtCore.QSize(40, 40))
        self.share_like_btn.setObjectName("share_like_btn")
        self.horizontalLayout_49.addWidget(self.share_like_btn)
        self.share_comment_btn = QtWidgets.QPushButton(Frame)
        self.share_comment_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    icon-size: 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);  /* 半透明黑色遮罩 hover */\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}\n"
"")
        self.share_comment_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\code\\zhuanti\\app\\AI-Yoga-Coach\\icons/comment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.share_comment_btn.setIcon(icon1)
        self.share_comment_btn.setIconSize(QtCore.QSize(40, 40))
        self.share_comment_btn.setObjectName("share_comment_btn")
        self.horizontalLayout_49.addWidget(self.share_comment_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem4)
        self.verticalLayout_24.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        spacerItem5 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem5)
        self.likeCount = QtWidgets.QLabel(Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.likeCount.setFont(font)
        self.likeCount.setText("")
        self.likeCount.setObjectName("likeCount")
        self.horizontalLayout_56.addWidget(self.likeCount)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem6)
        self.verticalLayout_24.addLayout(self.horizontalLayout_56)
        self.verticalLayout_24.setStretch(0, 1)
        self.verticalLayout_24.setStretch(1, 1)
        self.verticalLayout_24.setStretch(2, 1)
        self.verticalLayout_24.setStretch(3, 1)
        self.verticalLayout_24.setStretch(4, 1)
        self.verticalLayout.addLayout(self.verticalLayout_24)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
import resource_rc
